services:
  app:
    build: . # 使用同一個專案目錄中的 Dockerfile 建立映像
    working_dir: /app
    volumes:
      - .:/app
      # - /app/node_modules # 如果想使用 Dockerfile 裡面安裝好的 node_modules，可以移除這行
    ports:
      - "3001:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=CRM
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: coupon_db
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=CRM
      - MYSQL_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
